discourse_plugin_matching:
  practice_matching_enabled:
    default: true
    client: true
    description: "practice_matching_enabled"
    category: "plugins"
  practice_matching_min_trust_level:
    default: 0
    client: true
    enum: "TrustLevelSetting"
    description: "practice_matching_min_trust_level"
    category: "plugins" 